# Generated by Django 5.0.6 on 2025-11-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_real', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('preprocessing_info', models.JSONField(blank=True, default=dict)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='uploads.uploadedimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
