# Generated by Django 5.0.6 on 2025-11-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heatmap_image', models.ImageField(upload_to='xai/')),
                ('method', models.CharField(default='GradCAM', max_length=50)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='detection.detectionresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
